export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const POST_ERROR = 'POST_ERROR';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const DELETE_POST = 'DELETE_POST';
export const ADD_POST = 'ADD_POST';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';

// for college

export const COLLEGE_REGISTER_SUCCESS = 'COLLEGE_REGISTER_SUCCESS';
export const COLLEGE_REGISTER_FAIL = 'COLLEGE_REGISTER_FAIL';
export const COLLEGE_USER_LOADED = 'COLLEGE_USER_LOADED';
export const COLLEGE_AUTH_ERROR = 'COLLEGE_AUTH_ERROR';
export const COLLEGE_LOGIN_SUCCESS = 'COLLEGE_LOGIN_SUCCESS';
export const COLLEGE_LOGIN_FAIL = 'COLLEGE_LOGIN_FAIL';
export const COLLEGE_LOGOUT = 'COLLEGE_LOGOUT';
export const COLLEGE_CLEAR_PROFILE = 'COLLEGE_CLEAR_PROFILE';

export const COLLEGE_GET_PROFILE = 'COLLEGE_GET_PROFILE';
export const COLLEGE_GET_PROFILES = 'COLLEGE_GET_PROFILES';
export const COLLEGE_PROFILE_ERROR = 'COLLEGE_PROFILE_ERROR';
export const COLLEGE_ACCOUNT_DELETED = 'COLLEGE_ACCOUNT_DELETED';
